"""initial: extensions, five Phase 0 tables, and 19 app_settings seed rows

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-17

This is the single Phase 0 mega-migration (CONTEXT D-02). It runs three
``CREATE EXTENSION IF NOT EXISTS`` statements FIRST (FOUND-06; CONTEXT D-03)
because ``users.username`` and ``users.email`` are ``citext`` and the type
must be installed before the column is referenced.

Five tables (load-bearing decisions):

* ``users``               — referenced by ai_recommendations + wishlist_entries
* ``bags``                — coffee_id is BigInteger NOT NULL with NO FK
                            (CAT-04; FK added in Phase 4's migration when
                            coffees exists)
* ``wishlist_entries``    — present from day one per CONTEXT D-01
* ``ai_recommendations``  — full AI-02 column set INCLUDING all 11 COST-1
                            cost-observability columns (this is the
                            load-bearing assertion of Plan 00-03)
* ``app_settings``        — seeded with 19 documented rows (CONTEXT D-17)

Downgrade leaves the three extensions in place — they are cluster-shared
and dropping them could break other databases on the same Postgres
instance (RESEARCH §Schema Design §downgrade).

Per Plan 00-03 §Action: this file is hand-authored, NOT autogenerated.
Autogenerate emits neither ``CREATE EXTENSION`` nor correct index ordering
across tables.

Requirements traceability:
* FOUND-05 — single Alembic head, runs from entrypoint.sh
* FOUND-06 — citext / pg_trgm / unaccent extensions installed
* CAT-04   — bags table with the 9 spec columns
* AI-02    — ai_recommendations with the full column set + COST-1 columns
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Install extensions, create five tables, seed 19 app_settings rows."""
    # ---- 1) Postgres extensions (FOUND-06; CONTEXT D-03) ----------------
    # Idempotent via IF NOT EXISTS — safe to re-run. Must precede the
    # users table because username/email use the citext type.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ---- 2) users -------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column("username", postgresql.CITEXT(), nullable=False, unique=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("password_hash", sa.Text, nullable=False),
        sa.Column("is_admin", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("last_login_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # Partial unique index: multiple NULLs allowed, but if set, unique.
    op.create_index(
        "ix_users_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )

    # ---- 3) bags (CAT-04) -----------------------------------------------
    # bags.coffee_id FK constraint is deferred to Phase 4 when coffees
    # table exists. Ship as BigInteger NOT NULL so Phase 4 can ADD the FK
    # without re-tightening nullability on a populated table.
    op.create_table(
        "bags",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column("coffee_id", sa.BigInteger, nullable=False),
        sa.Column("roast_date", sa.Date, nullable=True),
        sa.Column("weight_grams", sa.Integer, nullable=True),
        sa.Column("opened_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("notes", sa.Text, nullable=False, server_default=""),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_bags_coffee_id", "bags", ["coffee_id"])

    # ---- 4) wishlist_entries (CONTEXT D-01) -----------------------------
    op.create_table(
        "wishlist_entries",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column(
            "user_id",
            sa.BigInteger,
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("coffee_name", sa.Text, nullable=False),
        sa.Column("roaster_name", sa.Text, nullable=True),
        sa.Column("source_url", sa.Text, nullable=True),
        # 'ai_recommendation' | 'manual' (free-form text by design)
        sa.Column("source", sa.Text, nullable=True),
        sa.Column("notes", sa.Text, nullable=False, server_default=""),
        sa.Column(
            "added_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("purchased_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.create_index("ix_wishlist_entries_user_id", "wishlist_entries", ["user_id"])

    # ---- 5) ai_recommendations (AI-02 + COST-1) -------------------------
    # All 11 cost-observability columns ship NOW, even though writes don't
    # begin until Phase 7. Retrofitting columns onto a populated table is
    # painful; the cost of shipping them empty for six phases is negligible.
    op.create_table(
        "ai_recommendations",
        sa.Column("id", sa.BigInteger, sa.Identity(always=False), primary_key=True),
        sa.Column(
            "user_id",
            sa.BigInteger,
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # enum-as-text: 'coffee' | 'equipment' | 'paste_rank' | 'sweet_spots'
        sa.Column("recommendation_type", sa.Text, nullable=False),
        sa.Column("input_signature", sa.Text, nullable=False),
        sa.Column("response_json", postgresql.JSONB, nullable=False),
        # 'anthropic' | 'openai'
        sa.Column("provider_used", sa.Text, nullable=False),
        sa.Column("model_used", sa.Text, nullable=False),
        # e.g. 'web_search_20260209' (Anthropic) or 'web_search' (OpenAI)
        sa.Column("tool_version", sa.Text, nullable=True),
        # COST-1 columns:
        sa.Column("tokens_input", sa.Integer, nullable=False, server_default="0"),
        sa.Column("tokens_output", sa.Integer, nullable=False, server_default="0"),
        sa.Column("tokens_input_search", sa.Integer, nullable=False, server_default="0"),
        sa.Column("web_search_count", sa.Integer, nullable=False, server_default="0"),
        # Null until URL-verification background task runs.
        sa.Column("url_verified", sa.Boolean, nullable=True),
        sa.Column("duration_ms", sa.Integer, nullable=True),
        sa.Column(
            "generated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        # 'scheduler' | 'manual_refresh'
        sa.Column("generated_by", sa.Text, nullable=False),
        sa.Column("error_status", sa.Text, nullable=True),
    )
    op.create_index("ix_ai_recs_input_signature", "ai_recommendations", ["input_signature"])
    op.create_index(
        "ix_ai_recs_user_type_generated",
        "ai_recommendations",
        ["user_id", "recommendation_type", sa.text("generated_at DESC")],
    )

    # ---- 6) app_settings (CONTEXT D-17) ---------------------------------
    op.create_table(
        "app_settings",
        sa.Column("key", sa.Text, primary_key=True),
        sa.Column("value", sa.Text, nullable=True),
        # 'string' | 'int' | 'float' | 'bool' | 'json' | 'null'
        sa.Column("value_type", sa.Text, nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_by_user_id",
            sa.BigInteger,
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )

    # ---- 7) Seed app_settings (19 rows; CONTEXT D-17) -------------------
    # Lightweight sa.table() used here so the migration is self-contained
    # and does NOT depend on the SQLAlchemy ORM model classes (Alembic-safe
    # pattern: never import from app.models inside a migration body).
    app_settings_table = sa.table(
        "app_settings",
        sa.column("key", sa.Text),
        sa.column("value", sa.Text),
        sa.column("value_type", sa.Text),
        sa.column("description", sa.Text),
    )

    op.bulk_insert(
        app_settings_table,
        [
            {
                "key": "recommendation_region",
                "value": "US",
                "value_type": "string",
                "description": (
                    "Geographic scope for live coffee search; "
                    "comma-separated region codes or 'any'."
                ),
            },
            {
                "key": "min_sessions_for_ai",
                "value": "3",
                "value_type": "int",
                "description": (
                    "AI-7 cold-start gate: minimum brew_sessions count per user."
                ),
            },
            {
                "key": "min_flavor_notes_for_ai",
                "value": "5",
                "value_type": "int",
                "description": (
                    "AI-7 cold-start gate: minimum distinct flavor_notes observed per user."
                ),
            },
            {
                "key": "ai_primary_max_searches",
                "value": "5",
                "value_type": "int",
                "description": "COST-5: max_uses cap for primary web-search.",
            },
            {
                "key": "ai_broadened_max_searches",
                "value": "3",
                "value_type": "int",
                "description": "COST-5: max_uses cap for broadened fallback.",
            },
            {
                "key": "ai_tool_version_anthropic",
                "value": "web_search_20260209",
                "value_type": "string",
                "description": (
                    "AI-5: Anthropic web-search tool version; editable from admin."
                ),
            },
            {
                "key": "ai_tool_version_openai",
                "value": "web_search",
                "value_type": "string",
                "description": "AI-5: OpenAI web-search tool version (non-preview).",
            },
            {
                "key": "ai_provider_default",
                "value": "anthropic",
                "value_type": "string",
                "description": "Default AI provider when both keys are enabled.",
            },
            {
                "key": "last_ai_run_status",
                "value": "never_run",
                "value_type": "string",
                "description": (
                    "COST-3: last AI scheduler run status; surfaced in admin health panel."
                ),
            },
            {
                "key": "last_backup_status",
                "value": "never_run",
                "value_type": "string",
                "description": "Phase 8 health panel.",
            },
            {
                "key": "last_backup_at",
                "value": None,
                "value_type": "null",
                "description": "Phase 8 health panel.",
            },
            {
                "key": "setup_completed",
                "value": "false",
                "value_type": "bool",
                "description": "SEC-5: read under SELECT...FOR UPDATE by /setup.",
            },
            {
                "key": "photo_max_bytes",
                "value": "5242880",
                "value_type": "int",
                "description": "Phase 4: max bag photo upload size (bytes); 5 MiB.",
            },
            {
                "key": "csv_import_max_rows",
                "value": "5000",
                "value_type": "int",
                "description": "Phase 5: max rows accepted per brew session CSV import.",
            },
            {
                "key": "home_recent_brews_limit",
                "value": "10",
                "value_type": "int",
                "description": "Phase 6: how many recent brews on home page.",
            },
            {
                "key": "home_top_coffees_limit",
                "value": "5",
                "value_type": "int",
                "description": "Phase 6: top-N coffees by avg rating.",
            },
            {
                "key": "home_top_coffees_min_sessions",
                "value": "2",
                "value_type": "int",
                "description": "Phase 6: minimum sessions for a coffee to qualify.",
            },
            {
                "key": "home_top_flavors_min_rating",
                "value": "4.0",
                "value_type": "float",
                "description": "Phase 6: rating floor for top-flavor-descriptors query.",
            },
            {
                "key": "home_sweetspot_min_sessions",
                "value": "3",
                "value_type": "int",
                "description": "Phase 6: minimum sessions for a sweet-spot cell.",
            },
        ],
    )


def downgrade() -> None:
    """Drop the five tables in reverse creation order.

    Extensions (citext / pg_trgm / unaccent) are intentionally left in
    place — they are cluster-shared and dropping them could break sibling
    databases on the same Postgres instance.
    """
    op.drop_table("app_settings")
    op.drop_index("ix_ai_recs_user_type_generated", table_name="ai_recommendations")
    op.drop_index("ix_ai_recs_input_signature", table_name="ai_recommendations")
    op.drop_table("ai_recommendations")
    op.drop_index("ix_wishlist_entries_user_id", table_name="wishlist_entries")
    op.drop_table("wishlist_entries")
    op.drop_index("ix_bags_coffee_id", table_name="bags")
    op.drop_table("bags")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
